IF NOT EXISTS(SELECT [ReportName] FROM [sys_Report]  WHERE [ReportID] = '20160318104829290')
BEGIN
	INSERT [sys_Report] ([ReportID], [ReportName], [Description], [ISOCode], [ReportFile], [ReportType], [Command], [MarginTop], [MarginLeft], [MarginRight], [MarginBottom], [MarginGutter], [MarginGutterPos], [Orientation], [PaperSize], [TableBorder], [Signatures], [FontReportHeader], [FontParameter], [FontPageHeader], [FontGroupBy], [FontDetail], [FontPageFooter], [FontReportFooter], [UseTemplate], [TemplateFile]) VALUES (N'20160318104829290', N'Sale Order Invoice By Date', N'', N'', N'InvoiceForSaleOrderReport.cs', N'C# File', N'[InvoiceForSaleOrderReport]-[InvoiceForSaleOrderReport.InvoiceForSaleOrderReport]-[ExecuteReport(@Day,@Customer,@SaleType,@ShipToLoc, @ConfirmId,@DocumentNo,@MakeType)]', 0, 0, 0, 0, 0, 0, 0, 8, 0, N'', N'Arial Narrow|12|Bold|1|False|Point', N'Arial Narrow|6|Bold|1|False|Point', N'Arial Narrow|6.5|Bold|1|False|Point', N'Arial Narrow|6|Bold|1|False|Point', N'Arial Narrow|6|Regular|1|False|Point', N'Arial Narrow|6|Regular|1|False|Point', N'Arial Narrow|6|Regular|1|False|Point', 0, N'Invoice4SaleOrderByDay.xml')
	SET IDENTITY_INSERT [dbo].[sys_ReportAndGroup] ON

	INSERT [sys_ReportAndGroup] ([ReportAndGroupID], [GroupID], [ReportID], [ReportOrder]) VALUES (160, N'20051222150154153', N'20160318104829290', 15)

	SET IDENTITY_INSERT [dbo].[sys_ReportAndGroup] OFF


	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'AVGPrice', 8, N'AVGPrice', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'AVGPrice', N'AVGPrice', N'AVGPrice', 15, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'BankAccountName', 22, N'BankAccountName', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'BankAccountName', N'BankAccountName', N'BankAccountName', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'BankAccountNo', 21, N'BankAccountNo', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'BankAccountNo', N'BankAccountNo', N'BankAccountNo', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ConfirmShipDetailID', 26, N'ConfirmShipDetailID', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ConfirmShipDetailID', N'ConfirmShipDetailID', N'ConfirmShipDetailID', 9, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ConfirmShipNo', 14, N'ConfirmShipNo', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ConfirmShipNo', N'ConfirmShipNo', N'ConfirmShipNo', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'CustomerPurchaseOrderNo', 25, N'CustomerPurchaseOrderNo', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'CustomerPurchaseOrderNo', N'CustomerPurchaseOrderNo', N'CustomerPurchaseOrderNo', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'DeliveryQuantity', 7, N'DeliveryQuantity', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'DeliveryQuantity', N'DeliveryQuantity', N'DeliveryQuantity', 15, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'InvoiceNo', 13, N'InvoiceNo', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'InvoiceNo', N'InvoiceNo', N'InvoiceNo', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ITM_ProductCode', 2, N'ITM_ProductCode', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ITM_ProductCode', N'ITM_ProductCode', N'ITM_ProductCode', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ITM_ProductDescription', 3, N'ITM_ProductDescription', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ITM_ProductDescription', N'ITM_ProductDescription', N'ITM_ProductDescription', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ITM_ProductDescriptionVN', 4, N'ITM_ProductDescriptionVN', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ITM_ProductDescriptionVN', N'ITM_ProductDescriptionVN', N'ITM_ProductDescriptionVN', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ITM_ProductRevision', 6, N'ITM_ProductRevision', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ITM_ProductRevision', N'ITM_ProductRevision', N'ITM_ProductRevision', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_PartyAddress', 17, N'MST_PartyAddress', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_PartyAddress', N'MST_PartyAddress', N'MST_PartyAddress', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_PartyBankAccount', 18, N'MST_PartyBankAccount', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_PartyBankAccount', N'MST_PartyBankAccount', N'MST_PartyBankAccount', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_PartyBankName', 19, N'MST_PartyBankName', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_PartyBankName', N'MST_PartyBankName', N'MST_PartyBankName', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_PartyName', 16, N'MST_PartyName', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_PartyName', N'MST_PartyName', N'MST_PartyName', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_PartyTaxCode', 20, N'MST_PartyTaxCode', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_PartyTaxCode', N'MST_PartyTaxCode', N'MST_PartyTaxCode', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'MST_UnitOfMeasureCode', 5, N'MST_UnitOfMeasureCode', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'MST_UnitOfMeasureCode', N'MST_UnitOfMeasureCode', N'MST_UnitOfMeasureCode', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'NetAmount', 10, N'NetAmount', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'NetAmount', N'NetAmount', N'NetAmount', 15, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ProductID', 1, N'ProductID', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ProductID', N'ProductID', N'ProductID', 9, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'SaleType', 23, N'SaleType', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'SaleType', N'SaleType', N'SaleType', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'SaleType1', 28, N'SaleType1', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'SaleType1', N'SaleType1', N'SaleType1', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ShippedDate', 15, N'ShippedDate', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ShippedDate', N'ShippedDate', N'ShippedDate', 16, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'ShipToLocation', 27, N'ShipToLocation', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'ShipToLocation', N'ShipToLocation', N'ShipToLocation', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'SOGate', 24, N'SOGate', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'SOGate', N'SOGate', N'SOGate', 18, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'UnitPrice', 9, N'UnitPrice', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'UnitPrice', N'UnitPrice', N'UnitPrice', 15, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'VatAmount', 12, N'VatAmount', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'VatAmount', N'VatAmount', N'VatAmount', 15, 3)

	INSERT [dbo].[sys_ReportFields] ([ReportID], [FieldName], [FieldOrder], [FieldCaption], [Font], [Visisble], [Type], [PrintReason], [PrintPreview], [Width], [Format], [ReportFormat], [Sort], [GroupBy], [BottomGroup], [SumTopPage], [SumBottomPage], [SumTopReport], [SumBottomReport], [FieldCaptionEN], [FieldCaptionVN], [FieldCaptionJP], [DataType], [Align]) VALUES (N'20160318104829290', N'VATPercent', 11, N'VATPercent', N'', 1, 0, 1, 0, 720, N'', NULL, 0, 0, 0, 0, 0, 0, 0, N'VATPercent', N'VATPercent', N'VATPercent', 15, 3)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@ConfirmId', 5, N'Confirm Ship No', 9, 1, 1, 0, 0, N'', N'', N'v_SOConfirmShipMaster', N'ConfirmShipMasterID', N'ConfirmShipNo', 100, N'SaleOrder', 150, N'', N'', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@Customer', 2, N'Customer', 9, 1, 1, 0, 0, N'', N'', N'MST_Party', N'PartyID', N'Code', 100, N'Name', 150, N'', N'MST_Party.Type <> 1', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@Day', 1, N'Day', 16, 100, 0, 0, 0, N'', N'', N'', N'', N'', 0, N'', 0, N'', N'', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@DocumentNo', 6, N'Document Number', 18, 1, 1, 0, 0, N'', N'', N'v_SOConfirmShipMaster', N'DocumentNumber', N'DocumentNumber', 100, NULL, 0, N'', N'', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@MakeType', 7, N'Car/Motorbike', 18, 100, 1, 0, 0, N'Both', N'Car#Motorbike#Both', N'', N'', N'', 0, N'', 0, N'', N'', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@SaleType', 3, N'Sale Type', 9, 1, 1, 0, 0, N'', N'', N'SO_SaleType', N'SaleTypeID', N'Code', 100, N'Description', 150, N'', N'', 0)

	INSERT [dbo].[sys_ReportPara] ([ReportID], [ParaName], [ParaOrder], [ParaCaption], [DataType], [Width], [Optional], [TagValue], [SameRow], [DefaultValue], [Items], [FromTable], [FromField], [FilterField1], [FilterField1Width], [FilterField2], [FilterField2Width], [SQLCLause], [WhereClause], [MultiSelection]) VALUES (N'20160318104829290', N'@ShipToLoc', 4, N'Ship to location', 9, 1, 1, 0, 0, N'', N'', N'MST_PartyLocation', N'PartyLocationID', N'Code', 100, N'Description', 150, N'', N'MST_PartyLocation.PartyID = @Customer', 0)

END
GO

IF NOT EXISTS (SELECT Menu_EntryID FROM Sys_Menu_Entry  WHERE [ReportID] = '20160318104829290')
BEGIN
	INSERT INTO [dbo].[Sys_Menu_Entry] ([Parent_Shortcut], [Shortcut], [Button_Caption], [Text_CaptionDefault], [Text_Caption_VI_VN], [Text_Caption_EN_US], [Text_Caption_JA_JP], [Text_Caption_Language_Default], [Parent_Child], [FormLoad], [Description], [Type], [CollapsedImage], [ExpandedImage], [Prefix], [TransFormat], [IsTransaction], [IsUserCreated], [TableName], [TransNoFieldName], [ReportID] )
	 VALUES ( 'SRPT', 'RPSOIBD', 51, 'Sale Order Invoice By Date', 'Sale Order Invoice By Date (vn)', 'Sale Order Invoice By Date (en)', 'Sale Order Invoice By Date (jp)', 'en_US', 3, 'PCSUtils.Framework.ReportFrame.ViewReport', NULL, 0, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, '20160318104829290' )
END